# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - none

pool:
    vmImage: 'windows-latest'

variables:
    buildPlatforms: 'Any CPU'
    buildConfiguration: 'Release'
    solution: '**/RoundTheCode.AzureTestProject.sln'
    project: '**/RoundTheCode.AzureTestProject.csproj'

steps:


- task: NuGetCommand@2
  displayName : 'Restore Nuget Packages '
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Application'
  inputs:
    command: 'build'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Application'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'

